# Generated by Django 2.2.3 on 2019-07-24 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script_name', models.CharField(max_length=30, unique=True)),
                ('script_path', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('IN_PROCESS', 'Processing'), ('NOT_STARTED', 'Not_yet_started'), ('SUCCESSFUL', 'Finished_succesfully'), ('FAILURE', 'Failed')], default='NOT_STARTED', max_length=30)),
                ('started_at', models.DateTimeField(null=True)),
                ('priority', models.IntegerField()),
                ('schedule_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_name', models.CharField(max_length=30, unique=True)),
                ('script', models.ForeignKey(on_delete=models.SET(0), related_name='script', to='jobs.Script')),
            ],
        ),
    ]
