# Generated by Django 2.2.3 on 2019-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_result_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='result_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
