# Generated by Django 2.2.3 on 2019-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190725_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='log_location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
