# Generated by Django 2.2.3 on 2019-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_log_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'Processing'), ('NOT_STARTED', 'Not_yet_started'), ('SUCCESSFUL', 'Finished_succesfully'), ('FAILURE', 'Failed'), ('TAKENQ', 'Taken_by_Q')], default='NOT_STARTED', max_length=30),
        ),
    ]
